### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by 617617** [DefuLi/Emotional-Analysis-of-Internet-News#1]
ValueError: could not convert string to float: b'xmlns="http://www.mediawiki.org/xml/export-0.10/"'

**Comment by DefuLi** [comment]
请把问题描述清楚

**Comment by 617617** [comment]
十万分感谢您的回复...我以为不会有人回复就抱着试着的心里发了一下....多谢大佬的开源代码，我因为没有您原来的训练好的语料库，所以用了自己的预训练语料库。
vects =torchtext.vocab.Vectors(name='G:/zhwiki-latest-pages-articles.xml')
然后在跑程序的时候报错
![image](https://user-images.githubusercontent.com/49274447/66974168-e9527280-f0cc-11e9-8682-23415ccbc6a0.png)

**Comment by DefuLi** [comment]
vects=torchtext.vocab.Vectors(name='wordfiles/Sgns.context.wordword.dynwin5.thr10.neg5.dim300.iter5.txt', cache='cachefiles/')

这个词向量文件Sgns.context.wordword.dynwin5.thr10.neg5.dim300.iter5.txt  请在这个链接中进行下载。https://pan.baidu.com/s/1svFOwFBKnnlsqrF1t99Lnw

**Comment by 617617** [comment]
![image](https://user-images.githubusercontent.com/49274447/66974796-e9537200-f0ce-11e9-914b-bf8b7569f5fd.png)
是这个吧 我是小白 万分感谢您的回复

**Comment by DefuLi** [comment]
是的，下载下来，解压，应该能看到一个txt文件。如果没有txt文件，你只需要把300多兆的文件后缀名改为txt就行，可以把这个文件放在pycharm里打开，这样打开速度比较快。
打开后，检查一下是不是词向量表。 就是每个字符都对应一大串向量。
