### ISSUE TITLE
我有两个问题请教下，谢谢

### ISSUE THREAD

**Issue by yudi941210** [DefuLi/Emotional-Analysis-of-Internet-News#5]
1.最后运行完得到的endclass.csv，里面有id这个字段，看到有注释是 #将id中的数值转换为真实的id文本，用的测试数据是test.csv,但是比对结果不方便看，是否应该把test.csv的id添加进来，不知道你们最后是怎么比对的

2.我要测试别的文章的话，分词后还是要写成test.csv文件，其它的不改，是这样的吗？也就是我该如何测试自己的文章

我也是刚涉及到文章情感分析这块，也是小白一个，谢谢了

**Comment by DefuLi** [comment]
第一个问题：因为在使用torchtext的时候，将id文本转换成了索引的形式，比如id=ab234asdfasdasdf，转换为0，所以最后测试完要从索引0转为id文本。

第二个问题：你如果测试别的文章，你可以把你的数据文件的格式，改成和我文件格式一样；也可以在我代码上修改，以适应你的文件。

**Comment by yudi941210** [comment]
非常感谢，我在继续学习！
