### ISSUE TITLE
您好，我下载了整个文件，但是数据集都损坏了，能发我一份吗，而且数据预处理生成的文件的id和源文件的id都不一样？能解释一下吗

### ISSUE THREAD

**Issue by zjt2020** [DefuLi/Emotional-Analysis-of-Internet-News#7]

**Comment by DefuLi** [comment]
在百度网盘上下载：


链接：https://pan.baidu.com/s/12NTWiIzZlQfRTyxNg7lUIQ&nbsp;
提取码：7s9n




姓名：李德福
 联系方式：18798750917


&nbsp;




------------------ 原始邮件 ------------------
发件人:&nbsp;"zjt2020"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月21日(星期天) 下午5:31
收件人:&nbsp;"DefuLi/Emotional-Analysis-of-Internet-News"<Emotional-Analysis-of-Internet-News@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[DefuLi/Emotional-Analysis-of-Internet-News] 您好，我下载了整个文件，但是数据集都损坏了，能发我一份吗 (#7)
