### ISSUE TITLE
请问能把运行结果发一下吗

### ISSUE THREAD

**Issue by zhujin-123** [DefuLi/Emotional-Analysis-of-Internet-News#8]
请问能把运行结果发一下吗

**Comment by DefuLi** [comment]
发不了，都已经过了挺久了，我的结果都删掉了。


---原始邮件---
发件人: &quot;zhujin-123&quot;<notifications@github.com&gt;
发送时间: 2020年6月27日(周六) 中午12:23
收件人: &quot;DefuLi/Emotional-Analysis-of-Internet-News&quot;<Emotional-Analysis-of-Internet-News@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: [DefuLi/Emotional-Analysis-of-Internet-News] 请问能把运行结果发一下吗 (#8)




 
请问能把运行结果发一下吗
 
&mdash;

**Comment by zhujin-123** [comment]
好吧，谢谢
