### ISSUE TITLE
报错RuntimeError: no vectors found at cachefiles/wordfiles/Sgns.context.word-word.dynwin5.thr10.neg5.dim300.iter5.txt

### ISSUE THREAD

**Issue by w2obin** [DefuLi/Emotional-Analysis-of-Internet-News#9]
你好 
我是新手 正在学习情感分析方面的内容
我在下载您的代码和百度云盘的数据后 出现了如下错误 请问该如何解决？ 谢谢
RuntimeError: no vectors found at cachefiles/wordfiles/Sgns.context.word-word.dynwin5.thr10.neg5.dim300.iter5.txt

**Comment by DefuLi** [comment]
这是少了词向量文件，你下载后放到正确的文件夹里就行。

![image](https://user-images.githubusercontent.com/33721251/91656319-75edff80-eaea-11ea-868d-f63550b0eb9f.png)
